### ISSUE TITLE
Add tooltips on the View Assessment page for detail on questions

### ISSUE THREAD

**Issue by trevorquinn** [redhat-cop/pathfinder-ui#5]
Sometimes I think we might forget the nature of the question when viewing application assessment details, so it would be good to have tooltips or similar detail on mouseover to get basic information on each of the question areas (Architectural Suitability, Clustering, Communication, etc.).

**Comment by matallen** [comment]
changed the view/review assessment page to include the original question & answer provided rather than just the rating numeral, so hopefully the context of the question and answer provided is much clearer now when going back to review an assessment.

If this hasn't satisfied your requirement, feel free to re-open this case.
